# Generated by Django 4.2.18 on 2025-03-23 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Your Deserve the best', max_length=255)),
                ('subtitle', models.TextField(default="YOUR FEET DESERVE THE BEST AND WE'RE HERE TO HELP YOU WITH OUR SHOES.")),
                ('prim_btn_clr', models.CharField(default='#FF0000', max_length=20)),
                ('sec_btn_clr', models.CharField(default='#FFFFFF', max_length=20)),
                ('avail_icon', models.JSONField(default='list')),
            ],
        ),
        migrations.CreateModel(
            name='Landing_Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('nav_items', models.JSONField(default=list)),
                ('login_btn_Text', models.CharField(default='Login', max_length=50)),
                ('login_btn_color', models.CharField(default='#FF0000', max_length=20)),
            ],
        ),
    ]
